runtime:
  generated_model_dir: D:\PhD\Workspace\Git_phd\phd\Article_Embedded_ML\dev\Benchmark\generated_models\random_forest\micromlgen
  generated_model_path: D:\PhD\Workspace\Git_phd\phd\Article_Embedded_ML\dev\Benchmark\generated_models\random_forest\micromlgen\model.h
  language: cpp
  model_name: random_forest
  no_of_features: 15
  porter_type: micromlgen
  template_path: D:\PhD\Workspace\Git_phd\phd\Article_Embedded_ML\dev\Benchmark\src\api\main.cpp
target:
  board: arduino_due_x
  compiler: arm
  compiler_stdout: false
  mcu: SAM3X8E
  monitor_port: '10'
  optimization_level: s
  ratio_test_samples_on_target: '20'
  sam_family: true
  type: arduino_makefile
training:
  accuracy: true
  class_accuracy: false
  dataset: HARDataLoader
  models_directory: generated_models
