runtime:
  generated_model_dir: D:\PhD\Workspace\Embedded_ML_Article_2\Workspace\mlino_bench\test_models\TestDecisionTreeClassifier\emlearn
  generated_model_path: D:\PhD\Workspace\Embedded_ML_Article_2\Workspace\mlino_bench\test_models\TestDecisionTreeClassifier\emlearn\model.h
  language: c
  model_name: TestDecisionTreeClassifier
  model_type: DecisionTreeClassifier
  no_of_features: 4
  porter_type: emlearn
  template_path: D:\PhD\Workspace\Embedded_ML_Article_2\Workspace\mlino_bench\src\api\main.cpp
target:
  board: mega
  compiler: gcc
  compiler_stdout: false
  mcu: atmega2560
  monitor_port: '8'
  optimization_level: s
  ratio_test_samples_on_target: '20'
  sam_family: false
  type: arduino_makefile
training:
  accuracy: false
  class_accuracy: false
  dataset: iris
  models_directory: test_models
  train_test_split: 0.8
