runtime:
  generated_model_dir: D:\PhD\Workspace\Git_phd\phd\Article_Embedded_ML\dev\Benchmark\generated_models\xgboost\m2cgen
  generated_model_path: D:\PhD\Workspace\Git_phd\phd\Article_Embedded_ML\dev\Benchmark\generated_models\xgboost\m2cgen\model.c
  language: c
  model_name: xgboost
  no_of_features: 128
  porter_type: m2cgen
  template_path: D:\PhD\Workspace\Git_phd\phd\Article_Embedded_ML\dev\Benchmark\src\api\main.cpp
target:
  board: mega
  board_sub: atmega2560
  compiler_stdout: false
  monitor_port: '9'
  optimization_level: s
  sam_family: false
  type: avr_gcc
training:
  accuracy: true
  class_accuracy: true
  default_dataset: GasDataLoader
  models_directory: generated_models
